### ISSUE TITLE
Ability to set a style to the logger

### ISSUE THREAD

**Issue by arsdever** [arsdever/qspdlog#35]
The functionality will allow the user to assign a style to the logger, so the log messages from that particular logger will show up in a user-defined way. For example, with a red background and green foreground colors.

Check out the second table at [`Qt::ItemDataRole`](https://doc.qt.io/qt-6/qt.html#ItemDataRole-enum)'s documentation.

**Comment by Overflwn** [comment]
Should I implement `Qt::FontRole` and `Qt::TextAlignmentRole` in #40 aswell?

**Comment by arsdever** [comment]
> Should I implement Qt::FontRole and Qt::TextAlignmentRole in https://github.com/arsdever/qspdlog/pull/40 aswell?

Probably, we should include `Qt::FontRole` as well, but maybe it can be implemented with a separate PR.

I'm thinking that we don't need to support `Qt::TextAlignmentRole` though. I don't see much use for it.

**Comment by arsdever** [comment]
Seems everything is covered.
